import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Clone of X",
	description: "Generated by X clone",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
